version: '3.8'

services:
  db:
    image: mysql:8.4
    container_name: pegachave-db
    restart: always
    environment:
      MYSQL_DATABASE: controle_chaves
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"

  web:
    build: .
    container_name: pegachave-web
    restart: always
    ports:
      - "8000:80"
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_NAME=controle_chaves
      - DB_USER=root
      - DB_PASS=
    depends_on:
      - db

volumes:
  db_data:
